//! Canonical serialization and hash helpers for contract-critical material.

use serde::Serialize;

use crate::sha256::sha256_hex;
use crate::ContractError;

/// Current canonical serialization policy version.
pub const CANONICAL_SERIALIZATION_VERSION: u32 = 1;

/// Serialize hash-critical material as compact UTF-8 JSON.
///
/// Policy v1 relies on concrete Rust structs with deterministic field order and
/// sorted containers (`BTreeMap`/sorted vectors) for set-like data. Unordered
/// maps are not part of hash material in this crate.
///
/// # Errors
/// Returns [`ContractError::Json`] if serialization fails.
#[must_use = "canonical bytes must be hashed or persisted"]
pub fn canonical_json_bytes<T: Serialize>(value: &T) -> Result<Vec<u8>, ContractError> {
    Ok(serde_json::to_vec(value)?)
}

/// Hash canonical JSON bytes as `sha256:<hex>`.
///
/// # Errors
/// Returns [`ContractError::Json`] if serialization fails.
#[must_use = "the content hash must be checked or persisted"]
pub fn canonical_json_hash<T: Serialize>(value: &T) -> Result<String, ContractError> {
    let bytes = canonical_json_bytes(value)?;
    Ok(format!("sha256:{}", sha256_hex(&bytes)))
}

/// Hash arbitrary generated bytes as `sha256:<hex>`.
#[must_use]
pub fn byte_hash(bytes: &[u8]) -> String {
    format!("sha256:{}", sha256_hex(bytes))
}
